version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    privileged: true
    volumes:
      - ..:/workspace:cached
      - /dev/bus/usb:/dev/bus/usb
      - backend_node_modules:/workspace/backend/node_modules
      - frontend_node_modules:/workspace/frontend/node_modules
    ports:
      - "3000:3000"
      - "5173:5173"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=nestbin
      - JWT_SECRET=a_very_strong_and_long_secret_key
      - PORT=3000
    depends_on:
      - db
    command: sleep infinity
    # network_mode: host

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nestbin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    # network_mode: host

volumes:
  postgres-data:
  backend_node_modules:
  frontend_node_modules:
